---
title: "git_00"
author: "Ramiro Rosas"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Girt with a boyish garb for boyish task,  
   Eager she wields her spade: yet loves as well  
Rest on the friendly knee, intent to ask  
         The tale one loves to tell.  
  
Rude scoffer of the seething outer strife,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
When I see birches bend to left and right  
Across the lines of straighter darker trees,  
I like to think some boy's been swinging them.  
But swinging doesn't bend them down to stay  
As ice-storms do. Often you must have seen them  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
      

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I met a traveller from an antique land,  
Who said—“Two vast and trunkless legs of stone  
Stand in the desert. . . . Near them, on the sand,  
Half sunk a shattered visage lies, whose frown,  
And wrinkled lip, and sneer of cold command,  
Tell that its sculptor well those passions read  
Which yet survive, stamped on these lifeless things,  
The hand that mocked them, and the heart that fed;  